### ISSUE TITLE
关于 lyric 特征和 chord 个数的疑问

### ISSUE THREAD

**Issue by rphao1995** [krystalan/MMCR#2]
你好，有幸拜读并复现了代码，测试集acc: 85.12%，有些疑问想请教一下。
1. 代码用 transformers 库直接提取了 lyric 特征，没有使用论文描述的 Graph Attention Networks ？
2. 论文 5.1 节提到，chord vocabulary size = 500，实际代码中只有 10 ？

**Comment by krystalan** [comment]
Hi，感谢你对我们的工作感兴趣，关于你的问题：
1. 我们自己下来又进行了消融实验分析，GAT所带来的收益不大，因此在代码中又去除掉了。
2. 这是因为和弦抽取模型（https://github.com/yashkhem1/Chord-Extraction-using-Machine-Learning ）只能对音乐文件抽取预定义的10种和弦（详见这里：https://github.com/yashkhem1/Chord-Extraction-using-Machine-Learning/blob/master/src/utilities.py#L18 ），因此我们也只保存了这10个和弦的embedding，其他的490个只是在训练embedding的时候一起进行计算，但并未在我们的任务中使用到，因此并未保存。

**Comment by rphao1995** [comment]
了解，谢谢 :)
